bind 127.0.0.1
port 6379
daemonize no
loglevel notice
logfile /var/log/mosgarage/redis.log
databases 4
save 900 1
save 300 10
save 60 10000
dir /var/lib/redis-mosgarage
maxmemory 256mb
maxmemory-policy allkeys-lru
appendonly yes
appendfilename "mosgarage.aof"
appendfsync everysec
protected-mode yes
tcp-keepalive 300
